### ISSUE TITLE
snn speakers

### ISSUE THREAD

**Issue by longjiang** [wooorm/speakers#6]
`snn: 1240000,`

Wikipedia says Siona (snn) has only 500 speakers 

https://en.wikipedia.org/wiki/Siona_language

**Comment by wooorm** [comment]
This seems to be a mix up by the united nations.
This definition: https://www.ohchr.org/EN/UDHR/Pages/Language.aspx?LangID=1121, talks about Bai Coca and Ecuador, whereas the text talks, and presumably gives a speaker count for, a Tibetan language.
You might want to report this to the OHCHR.
