### ISSUE TITLE
que speakers

### ISSUE THREAD

**Issue by longjiang** [wooorm/speakers#7]
`que: 30000,`

Wikipedia says Quechua (que) has about 8-10 million speakers

https://iso639-3.sil.org/code/qwc

https://en.wikipedia.org/wiki/Quechuan_languages#Classification

**Comment by wooorm** [comment]
This is the data that OHCHR provides: https://www.ohchr.org/EN/UDHR/Pages/Language.aspx?LangID=qud1.
It might be good to raise this issue with the united nations and/or the unicode consortium.
Closing as the goal of this project is to provide a baseline for hundreds of language based on a proper source, and wikipedia isn’t that.
